image:
  repository: registry.gitlab.com/eagledevstack/cat-proxy
  pullPolicy: IfNotPresent
  tag: "66f9cdd0"
  imagePullSecrets: []

replicaCount: 1

http:
  enabled: true
  type: ClusterIP
  protocol: TCP
  port: 8118
  targetPort: 8118
  ingress:
    enabled: false
    className: ""
    annotations: {}
    tls: []
    hosts:
      - host: http-example.local
        paths:
          - path: /
            pathType: Prefix

socks5:
  enabled: false
  type: ClusterIP
  protocol: TCP
  port: 9050
  targetPort: 9050
  ingress:
    enabled: false
    className: ""
    annotations: {}
    tls: []
    hosts:
      - host: socks5-example.local
        paths:
          - path: /
            pathType: Prefix
  volumeMounts: []
  resources: {}

dns:
  enabled: false
  type: ClusterIP
  protocol: TCP
  port: 5353
  targetPort: 5353
  ingress:
    enabled: false
    className: ""
    annotations: {}
    tls: []
    hosts:
      - host: dns-example.local
        paths:
          - path: /
            pathType: Prefix
  volumeMounts: []
  resources: {}

secretRef: ""

volumeMounts: []

resources: {}

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}
