{{- if or $.Values.http.enabled $.Values.socks5.enabled $.Values.dns.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" .Chart.Name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ printf "%s-app" .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-app" .Chart.Name }}
    spec:
      {{- with $.Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ printf "%s-container" .Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- with $.Values.secretRef }}
          envFrom:
            - secretRef:
                name: {{ $.Values.secretRef }}
          {{- end }}
          ports:
            {{- if $.Values.http.enabled }}
            - name: {{ printf "%s-http" $.Chart.Name }}
              containerPort: {{ .Values.http.targetPort }}
              protocol: {{ .Values.http.protocol }}
            {{- end }}
            {{- if $.Values.socks5.enabled }}
            - name: {{ printf "%s-socks5" $.Chart.Name }}
              containerPort: {{ .Values.socks5.targetPort }}
              protocol: {{ .Values.socks5.protocol }}
            {{- end }}
            {{- if $.Values.dns.enabled }}
            - name: {{ printf "%s-dns" $.Chart.Name }}
              containerPort: {{ .Values.dns.targetPort }}
              protocol: {{ .Values.dns.protocol }}
            {{- end }}
          {{- with $.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}